### ISSUE TITLE
Problem: Runtime.evaluate error `{ code: -32000, message: 'Cannot find context with specified id' }`

### ISSUE THREAD

**Issue by foreseaz** [nleak/nleak#60]
When running `Runtime.evaluate` from node driver:
```
[DEBUG node_driver] runCode:  $$$INSTRUMENT_PATHS$$$([{"isGrowing":true,"children":[],"type":1,"indexOrName":"LEAKOBJ","id":37484},{"isGrowing":false,"children":[{"isGrowing":false,"children":[{"isGrowing":false,"children":[{"isGrowing":false,"children":[{"isGrowing":true,"children":[],"type":1,"indexOrName":"list","id":35134}],"type":1,"indexOrName":"tail"}],"type":4,"indexOrName":"queue"}],"type":3,"indexOrName":"__scope__"}],"type":1,"indexOrName":"queueMicrotask"}])
failed to evaluate expression in child process ProtocolError: Cannot find context with specified id
    at /Users/chenxizh/workspace/practium/nleak/node_modules/chrome-remote-interface/lib/chrome.js:94:35
    at Chrome._handleMessage (/Users/chenxizh/workspace/practium/nleak/node_modules/chrome-remote-interface/lib/chrome.js:257:17)
    at WebSocket.<anonymous> (/Users/chenxizh/workspace/practium/nleak/node_modules/chrome-remote-interface/lib/chrome.js:235:22)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (/Users/chenxizh/workspace/practium/nleak/node_modules/ws/lib/websocket.js:1068:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.emit (node:domain:489:12)
    at Receiver.dataMessage (/Users/chenxizh/workspace/practium/nleak/node_modules/ws/lib/receiver.js:517:14)
    at Receiver.getData (/Users/chenxizh/workspace/practium/nleak/node_modules/ws/lib/receiver.js:435:17) {
  request: {
    method: 'Runtime.evaluate',
    params: {
      expression: '$$$INSTRUMENT_PATHS$$$([{"isGrowing":true,"children":[],"type":1,"indexOrName":"LEAKOBJ","id":37484},{"isGrowing":false,"children":[{"isGrowing":false,"children":[{"isGrowing":false,"children":[{"isGrowing":false,"children":[{"isGrowing":true,"children":[],"type":1,"indexOrName":"list","id":35134}],"type":1,"indexOrName":"tail"}],"type":4,"indexOrName":"queue"}],"type":3,"indexOrName":"__scope__"}],"type":1,"indexOrName":"queueMicrotask"}])',
      returnByValue: true
    },
    sessionId: undefined
  },
  response: { code: -32000, message: 'Cannot find context with specified id' }
}
```

**Comment by foreseaz** [comment]
closed by #61
